" Generated by vim-plug
" Thu Dec  5 11:30:54 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['compile-mode.nvim'].commit = '4feef0bd6485218f50563a61140233f16561c786'
silent! let g:plugs['copilot.vim'].commit = '87038123804796ca7af20d1b71c3428d858a9124'
silent! let g:plugs['diffview.nvim'].commit = '4516612fe98ff56ae0415a259ff6361a89419b0a'
silent! let g:plugs['fzf-lua'].commit = '175ddbb9bbe28eef006516f38b126215de1fef57'
silent! let g:plugs['gitsigns.nvim'].commit = '5f808b5e4fef30bd8aca1b803b4e555da07fc412'
silent! let g:plugs['mini.nvim'].commit = 'c8922aef8207137e66c80acdb9523668599ba62a'
silent! let g:plugs['neogit'].commit = '11e14b67eb19bada54c9eb8bc70a581f358cd175'
silent! let g:plugs['noice.nvim'].commit = 'c6f6fb178ebe9b4fd90383de743c3399f8c3a37c'
silent! let g:plugs['nui.nvim'].commit = 'b58e2bfda5cea347c9d58b7f11cf3012c7b3953f'
silent! let g:plugs['nvim'].commit = 'faf15ab0201b564b6368ffa47b56feefc92ce3f4'
silent! let g:plugs['nvim-bqf'].commit = '1b24dc6050c34e8cd377b6b4cd6abe40509e0187'
silent! let g:plugs['nvim-dap'].commit = '0a0daa796a5919a51e5e5019ffa91219c94c4fef'
silent! let g:plugs['nvim-dap-projects'].commit = 'f319ffd99c6c8a0b930bcfc4bee0c751ffbf5808'
silent! let g:plugs['nvim-dap-ui'].commit = 'ffa89839f97bad360e78428d5c740fdad9a0ff02'
silent! let g:plugs['nvim-neoclip.lua'].commit = '32e05f2d23dc5b6a284a688c0535a83d1bfc633f'
silent! let g:plugs['nvim-nio'].commit = 'a428f309119086dc78dd4b19306d2d67be884eee'
silent! let g:plugs['nvim-tree.lua'].commit = 'ca7c4c33cac2ad66ec69d45e465379716ef0cc97'
silent! let g:plugs['octo.nvim'].commit = 'd12e06866d55b3e6352ade761372dd5fcedb6bc9'
silent! let g:plugs['oil.nvim'].commit = '3c2de37accead0240fbe812f5ccdedfe0b973557'
silent! let g:plugs['plenary.nvim'].commit = '2d9b06177a975543726ce5c73fca176cedbffe9d'
silent! let g:plugs['sessions.nvim'].commit = 'f13158483e0b6255c6dfe473145ce4ee3495d844'
silent! let g:plugs['telescope-file-browser.nvim'].commit = '626998e5c1b71c130d8bc6cf7abb6709b98287bb'
silent! let g:plugs['telescope-fzf-native.nvim'].commit = 'cf48d4dfce44e0b9a2e19a008d6ec6ea6f01a83b'
silent! let g:plugs['telescope-live-grep-args.nvim'].commit = '649b662a8f476fd2c0289570764459e95ebaa3f3'
silent! let g:plugs['telescope.nvim'].commit = '2eca9ba22002184ac05eddbe47a7fe2d5a384dfc'
silent! let g:plugs['toggleterm.nvim'].commit = '87b2d6a3cab8e2bd9a0255427074285f0365398d'
silent! let g:plugs['which-key.nvim'].commit = '9b365a6428a9633e3eeb34dbef1b791511c54f70'
silent! let g:plugs['workspaces.nvim'].commit = '55a1eb6f5b72e07ee8333898254e113e927180ca'

PlugUpdate!

