" Generated by vim-plug
" Tue Nov 12 08:29:51 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['compile-mode.nvim'].commit = 'bb5e614bbfe8bc85dd9195767603ed2efb451750'
silent! let g:plugs['copilot.vim'].commit = '87038123804796ca7af20d1b71c3428d858a9124'
silent! let g:plugs['diffview.nvim'].commit = '4516612fe98ff56ae0415a259ff6361a89419b0a'
silent! let g:plugs['fzf-lua'].commit = 'ce1e24f2a48089b65deefcb0a71a9856839002b5'
silent! let g:plugs['gitsigns.nvim'].commit = '4daf7022f1481edf1e8fb9947df13bb07c18e89a'
silent! let g:plugs['neogit'].commit = '3987b02e6eb309de87e405a555086d259a153c42'
silent! let g:plugs['noice.nvim'].commit = '73d38cc939db6553b87e5f72ff732447046bced1'
silent! let g:plugs['nui.nvim'].commit = 'b58e2bfda5cea347c9d58b7f11cf3012c7b3953f'
silent! let g:plugs['nvim'].commit = '35d8057137af463c9f41f169539e9b190d57d269'
silent! let g:plugs['nvim-bqf'].commit = '1b24dc6050c34e8cd377b6b4cd6abe40509e0187'
silent! let g:plugs['nvim-dap'].commit = '8517126e9323e346f6a99b3b594c5a940b914dcd'
silent! let g:plugs['nvim-dap-projects'].commit = 'f319ffd99c6c8a0b930bcfc4bee0c751ffbf5808'
silent! let g:plugs['nvim-dap-ui'].commit = 'ffa89839f97bad360e78428d5c740fdad9a0ff02'
silent! let g:plugs['nvim-neoclip.lua'].commit = '32e05f2d23dc5b6a284a688c0535a83d1bfc633f'
silent! let g:plugs['nvim-nio'].commit = 'a428f309119086dc78dd4b19306d2d67be884eee'
silent! let g:plugs['nvim-surround'].commit = 'dca2e998ff26681ee422b92c6ed39b3d2908d8a9'
silent! let g:plugs['nvim-tree.lua'].commit = '610a1c189bdb2b9b936169b2ea9d1838f971fa2b'
silent! let g:plugs['octo.nvim'].commit = '44060b7ad1153d80ec2a30ebfaf9957d58d6c69e'
silent! let g:plugs['oil.nvim'].commit = '52cc8a1fb35ea6ce1df536143add7ce7215c63c0'
silent! let g:plugs['plenary.nvim'].commit = '2d9b06177a975543726ce5c73fca176cedbffe9d'
silent! let g:plugs['sessions.nvim'].commit = 'f13158483e0b6255c6dfe473145ce4ee3495d844'
silent! let g:plugs['telescope-file-browser.nvim'].commit = '626998e5c1b71c130d8bc6cf7abb6709b98287bb'
silent! let g:plugs['telescope-fzf-native.nvim'].commit = 'cf48d4dfce44e0b9a2e19a008d6ec6ea6f01a83b'
silent! let g:plugs['telescope-live-grep-args.nvim'].commit = '649b662a8f476fd2c0289570764459e95ebaa3f3'
silent! let g:plugs['telescope.nvim'].commit = '85922dde3767e01d42a08e750a773effbffaea3e'
silent! let g:plugs['toggleterm.nvim'].commit = '5969229c0352ff1ed7f6e24aba9c6554e1842939'
silent! let g:plugs['which-key.nvim'].commit = '68e37e12913a66b60073906f5d3f14dee0de19f2'
silent! let g:plugs['workspaces.nvim'].commit = '55a1eb6f5b72e07ee8333898254e113e927180ca'

PlugUpdate!

